include: package:flutter_lints/flutter.yaml

# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    non_constant_identifier_names: false
    sort_child_properties_last: false
    use_build_context_synchronously: false
    constant_identifier_names: false
    file_names: false
    unnecessary_this: false
    camel_case_types: false